logging:
  version: 1
  formatters:
    detailed:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: detailed
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: detailed
      filename: /var/log/kowka/operations.log
      maxBytes: 10485760
      backupCount: 5
      encoding: utf8
    secure_file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: detailed
      filename: /var/log/kowka/secure.log
      maxBytes: 5242880
      backupCount: 3
      encoding: utf8
  loggers:
    kowka:
      level: DEBUG
      handlers: [console, file, secure_file]
      propagate: no
    kowka.secure:
      level: DEBUG
      handlers: [secure_file]
      propagate: no
